name: Build and Deploy Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-nginx-app .

      - name: Log into Docker Hub
      run: |
      echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

  - name: Push Docker image to Docker Hub
    run: |
      docker tag my-nginx-app ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest
      docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest



#        run: docker login ${{ secrets.DOCKER_USERNAME }}
 #       env:
  #          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
 #     - name: Push Docker image to Docker Hub
  #      run: |
   #       docker tag my-nginx-app ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest
    #      docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest

